---
exclude: "^$"
fail_fast: false
repos:
  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: bash -c 'cargo fmt -- --config edition=2024'
        language: system
        types: [rust]
      - id: cargo-clippy
        name: cargo clippy
        entry: bash -c 'cargo clippy -- -D warnings'
        language: system
        types: [rust]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        exclude: '^.*\.svg$|^.*\.kicad_pcb$|^.*\.kicad_sch$|^.*\.kicad_mod$|^.*\.kicad_prl$'
        name: check for common misspelled words

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        exclude: ".github/.*"
        additional_dependencies:
          - mdformat-tables
          - mdformat-gfm
          - mdformat-gfm-alerts

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
        exclude: '^(\.vscode/.*\.json|cargo-generate/launch\.json)$'
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
        exclude: '^.*\.rs$'
      - id: check-symlinks
      - id: check-xml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.0
    hooks:
      - id: yamllint
        name: check yaml files with yamllint
        args: ["-c", ".yamllint.yaml"]
